# Generated by Django 3.0.4 on 2022-11-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0002_auto_20221110_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.CharField(default='1', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
