# Generated by Django 3.0.4 on 2022-11-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0003_auto_20221113_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_id',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='Payment ID'),
        ),
        migrations.AddField(
            model_name='booking',
            name='provider_order_id',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Order ID'),
        ),
        migrations.AddField(
            model_name='booking',
            name='signature_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Signature ID'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(default='Pending', max_length=254, verbose_name='Payment Status'),
        ),
    ]
