# Generated by Django 3.0.4 on 2022-11-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0005_product_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verified',
            field=models.CharField(default='False', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
